### ISSUE TITLE
Bower install failed to execute on Font-Awesome

### ISSUE THREAD

**Issue by slowmove** [appbaseio/mirage#1]
bower install sucessfully installs select2 as well as bootstrap but fails on Font Awesome
``` ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/FortAwesome/Font-Awesome.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Operation timed out ```

![skarmavbild 2016-03-18 kl 14 15 10](https://cloud.githubusercontent.com/assets/624182/13878787/ec8188b2-ed13-11e5-88ac-acbf056d3b1d.png)

**Comment by siddharthlatest** [comment]
@slowmove could have been because it was pre-alpha. It's now in alpha and the installation should work.

**Comment by siddharthlatest** [comment]
Closing this issue.
