### ISSUE TITLE
vendor.min.js:6 Uncaught ReferenceError: jQuery is not defined(anonymous function) ..

### ISSUE THREAD

**Issue by matarrese** [appbaseio/mirage#17]
Hi, 
I have been trying to run the instance locally.
When I open the browser, these are the errors that I get in the console:
vendor.min.js:6 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ vendor.min.js:6
JSONURL.js:1 Uncaught ReferenceError: LZMA is not defined(anonymous function) @ JSONURL.js:1
custom.min.js:1 Uncaught ReferenceError: $ is not defined

Am I missing any step in order to run it correctly?

**Comment by farhan687** [comment]
Hi @matarrese 

Are you using dev branch? 
-> If yes it looks like you forgot to do bower install. 
to resolve this do
1) bower install, 
2) npm run build.

Or if other than that can you tell me where do you see this problem in chrome_extension, elastic search plugin or gh-pages?

**Comment by matarrese** [comment]
Thank you
