### ISSUE TITLE
support filter clause in the compound query combinator

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/mirage#19]
Compound query combinator (denoted by `+ Nested query`) supports `must`, `should`, `must_not` and `should_not` (?) clauses.

`should_not` is not a valid clause. Using it throws a query syntax error.

![should_not use](https://i.imgur.com/l2WrqNS.png)

![Syntax Error](https://i.imgur.com/sgWY7WC.png)

The fourth clause should be `filter` instead of `should_not`. From the documentation for [filters clause in bool query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html), 

> The clause (query) must appear in matching documents. However unlike must the score of the query will be ignored.

**Comment by farhan687** [comment]
Fixed over here c883dd893512f0cb49d9d73cf3f3ccccd286ce70
