### ISSUE TITLE
use subfield in query

### ISSUE THREAD

**Issue by peppetrick** [appbaseio/mirage#20]
It seems  I cannot select subfield for a query in drop down menu..

**Comment by siddharthlatest** [comment]
@peppetrick That's not very clear. Can you elaborate and/or paste a screenshot of what you are trying to do?

**Comment by peppetrick** [comment]
Look one hits below, you see the field "**Evento**" with subfield...


![image](https://cloud.githubusercontent.com/assets/11177562/19305323/a06797b8-9070-11e6-96aa-f5e7ffc61789.png)

in the drop down menu I can see only "**Evento**"

![image](https://cloud.githubusercontent.com/assets/11177562/19305358/ca3f99aa-9070-11e6-82c9-5efeb34d5340.png)

**Comment by siddharthlatest** [comment]
@peppetrick Got it, we would like to support nested objects. Would this be useful in other queries besides the nested query?

**Comment by siddharthlatest** [comment]
I want to mention that subfields (in the multi-field context) are now supported. Not to be confused with nested object fields, which will be supported when we add nested query support. Filing an issue for that separately.
