### ISSUE TITLE
unable to connect in chrome extension 

### ISSUE THREAD

**Issue by laTruffe79** [appbaseio/mirage#21]
Hello mirage seems great but the chrome extension don't work I can't click connect the console output is 

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-g7ROzI+cQxT+UGWjoGEOx2zf/qXlg3zmEz469iJGn2E='), or a nonce ('nonce-...') is required to enable inline execution.

my chrome is on version 53.0.2785.116 m

**Comment by farhan687** [comment]
Ignore that error.
Did you type appname and url in the input boxes?
Can you share screenshot?

**Comment by siddharthlatest** [comment]
@laTruffe79 can you share a screenshot?

**Comment by siddharthlatest** [comment]
@laTruffe79 I am closing this because of the lack of updates.
