### ISSUE TITLE
Official Docker

### ISSUE THREAD

**Issue by jalberto** [appbaseio/mirage#23]
Will be great to have an official docker image for mirage, eg:

https://github.com/lmenezes/elasticsearch-kopf/tree/master/docker

**Comment by siddharthlatest** [comment]
@jalberto That's a good suggestion.

**Comment by hkulekci** [comment]
I can create a Dockerfile and docker-compose.yml file for the project.

**Comment by Analect** [comment]
@siddharthlatest 
Can I ask, is this dockerized version intended to be an alternative to installing it as a plugin?  As per #35, I was having trouble installing it on v5 of ES.

@hkulekci 
I can see the Dockerfile, as part of the CMD uses `--host=0.0.0.0` .. am I right in understanding that this should point to the host where ES is running?  Does it need to be running on the same machine as this container? Do you tend to run up this container as part of a larger docker-compose file that includes ES containers too ... and do any form of linkage or ensure they are on the same network?

Also, is it possible to use your approach to containerize appbaseio/dejavu too?

Thanks.

**Comment by hkulekci** [comment]
@Analect `--host` parameter doesn't mention ES host. It actually mentions node server ip address. By default, it points to your containers localhost. If you want to change, you can set. For development environment, it is not necessary. Also, I think, you will use your dist folder for production, not your node server or npm environment. 

On the other hand, Mirage provide a interface to set a host address from mirage interface(no need any configuration). For this reason, your mirage interface can be work if you are in the same network with your elasticsearch cluster.

**Comment by Analect** [comment]
Thanks @hkulekci 
Just a quick follow-up ... have you tried to containerize dejavu in the same way.  Do you see any obstacles to taking the same approach as you've done in here?

**Comment by hkulekci** [comment]
please check the pr for dejavu https://github.com/appbaseio/dejavu/pull/49 @Analect

**Comment by Analect** [comment]
Thanks alot @hkulekci

**Comment by siddharthlatest** [comment]
Thanks @hkulekci for the PR. Official images are now available at https://hub.docker.com/r/appbaseio/mirage/ and https://hub.docker.com/r/appbaseio/dejavu/!
