### ISSUE TITLE
GeoPolygon Query should accept an array

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/mirage#26]
A polygon shape can be defined by a n-size array, it's better to take the array as is rather than try to interpret individual (lat, long) values of the polygon shape.

![](https://i.imgur.com/7XXHAET.png)

**Comment by farhan687** [comment]
Fixed over here: 8a7808c343b4ece3545c79cdbebcb20364ed2c51

**Comment by siddharthlatest** [comment]
Released in `v0.3.0`
