### ISSUE TITLE
Show different results view

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/mirage#29]
We currently show the results as raw JSON. We can update this to show: 

1. Results in a tabular format,  
2. Streaming results (applicable for appbase.io hosted versions)

**Comment by siddharthlatest** [comment]
Results in tabular format are already supported in `v0.6.0`, streaming results support will be added in the next release.

**Comment by farhan687** [comment]
Fixed here: f9509fd081ae05bd899d90bb0cb5ed2ab977897a
