### ISSUE TITLE
Add streaming flag in queries

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/mirage#30]
We can add a stream -> `true`/`false` flag (could be implemented as a switch) in the main Mirage UI, the switch only shows when hostname is an appbase.io URL (and eventually will be supported in Autopilot too).

**Comment by farhan687** [comment]
Fixed here: f9509fd081ae05bd899d90bb0cb5ed2ab977897a 049fe257b99a443c3331ee236037e85d10d4fcfc
