### ISSUE TITLE
Support for index aliases

### ISSUE THREAD

**Issue by zpchavez** [appbaseio/mirage#31]
Mirage should have the option to select an index by its alias. When following the [zero down-time reindex pattern](https://www.elastic.co/blog/changing-mapping-with-zero-downtime), the index name will change with every reindexing, but the alias will remain the same. Currently this means all saved queries in Mirage will become invalid.

**Comment by siddharthlatest** [comment]
@zpchavez Yes, aliases should be supported instead of app name.

And also confirming the issue - currently, mirage returns a `401` error code.

![](https://i.imgur.com/LbKpGcv.png)

**Comment by siddharthlatest** [comment]
Fixed here https://github.com/appbaseio/mirage/commit/cd500ee069b9d2315d29b13b0e298819f16ef015.
