### ISSUE TITLE
Data View  and Query View button take me to appbase.io

### ISSUE THREAD

**Issue by fizerkhan** [appbaseio/mirage#32]
I installed mirage as plugin to my local elasticsearch. In the Mirage GUI, When I click "Data View" button, it goes to `http://opensource.appbase.io/dejavu/live/#?input_state=`. But it should go to local dejavu. By the way, I also installed dejavu locally. 

Similarly,  Query view button in dejavu takes to appbase.io mirage. But it should goes to local machine.
Is there way to configure it?

**Comment by siddharthlatest** [comment]
@fizerkhan The host name is what will change from the hosted app URL if you intend to use it with the local plugin. That said, we are considering how to integrate them more fluidly.

**Comment by fizerkhan** [comment]
@siddharthlatest You mean it is intended.

**Comment by weewey** [comment]
Is it possible we can point the Data View and Query View to take me to the locally installed deja vu?

I have tried to change the code at _mirage/app/result/result.component.ts_ and _mirage/app/shared/urlShare.ts_

to point it to http://localhost:1358/live/

**Comment by siddharthlatest** [comment]
@weewey The challenge is that we can't tell when a user has them locally installed. You should be able to trivially replace the host name of the shared URL with localhost and it should work.

**Comment by welchwilmerck** [comment]
Could you be more specific about how I might "trivially replace the host name of the shared URL"?  Do you mean under the share icon on the far left?  I can edit, but it doesn't save my changes.

I've gone with the chrome extension for both dejavu and mirage, so how do I get them to point to each other instead of appbase.io?
