### ISSUE TITLE
Can't connect to ES server

### ISSUE THREAD

**Issue by haizaar** [appbaseio/mirage#34]
Hi guys,

I'm using hosted version of Mirage: http://opensource.appbase.io/mirage/ on Chrome 53.

It can't connect to my dev server that does not have any auth and has CORS allow origin set to `*`:

![image](https://cloud.githubusercontent.com/assets/58201/20924160/cb5b4e2e-bbb8-11e6-8667-459947c07930.png)

Browser console says the following:
```
XMLHttpRequest cannot load http://example:9200/foobar/_mapping/. Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```

However my CORES response welcomes everybody:
```
Access-Control-Allow-Headers:Content-Type
Access-Control-Allow-Headers:Content-Length
Access-Control-Allow-Headers:X-Requested-With
Access-Control-Allow-Methods:DELETE
Access-Control-Allow-Methods:POST
Access-Control-Allow-Methods:GET
Access-Control-Allow-Methods:PUT
Access-Control-Allow-Methods:HEAD
Access-Control-Allow-Methods:OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Max-Age:1728000
Connection:keep-alive
Content-Length:0
Date:Tue, 06 Dec 2016 11:29:05 GMT
```

**Comment by haizaar** [comment]
Probably related: https://github.com/appbaseio/dejavu/issues/47

**Comment by farhan687** [comment]
Hey @haizaar Can you make sure you followed following steps: https://github.com/appbaseio/mirage#install-as-elasticsearch-plugin

and try `http.cors.allow-origin: "/.*/"` instead of just `*`

**Comment by haizaar** [comment]
Turns out I've missed `allow-headers` directive. Now it works wonders. Thank you!
