### ISSUE TITLE
Installing plugin version on ES 5.x

### ISSUE THREAD

**Issue by Analect** [appbaseio/mirage#35]
I was trying to install both the mirage and dejavu as plugins in the latest version of ES 5.1.1

However, I got the following error.
```
ERROR: Unknown plugin appbaseio/mirage
The command '/bin/sh -c elasticsearch-plugin install appbaseio/mirage' returned a non-zero code: 64
```

The install command I ran, from a Dockerfile using `FROM elasticsearch:5.1.1-alpine` was `RUN elasticsearch-plugin install appbaseio/mirage`.  This approach worked fine for other plugins.

However it doesn't appear to recognise you plugin. Is there some requirement that they be uploaded to elastic infrastructure somewhere ... or is there an alternative approach of referencing the plugin location, such as with a github url?

I see this approach of installing a plugin directly from github .. but I think it requires there to be a binary on available as part of the release, which I don't think is the case with this repo.

`/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/5.1.1.0/elasticsearch-sql-5.1.1.0.zip`
Thanks.

**Comment by siddharthlatest** [comment]
ES has removed support for site plugins v5.0 onwards. Alternatives are to:

1. Run the plugin on a standalone server
2. Run via docker https://hub.docker.com/r/appbaseio/mirage/.

Both scenarios require adding [CORS config](https://github.com/appbaseio/mirage#install-as-elasticsearch-plugin) in Elasticsearch, similar to the one required for plugin installation.
